spring:
  security:
    oath2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/new_realm
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081